[1] aiGoalFollowWayPts::Update()
Notes
1) Code compiles in Debug mode and runs fine in-game at first glance (e.g. change "Car->Sim.ICS.AngularMomentum *= 0.1f;")
2) Doesn't compile in Final mode:
	...\mmai\aiGoalFollowWayPts.cpp(138,59): error C2220: the following warning is treated as an error
	...\mmai\aiGoalFollowWayPts.cpp(138,59): warning C4244: '=': conversion from 'i32' to 'i16', possible loss of data
3) IDA suggest "f32 arg10" instead of the current "i16 arg10" for the function "DetermineOppMapComponent"